### ISSUE TITLE
[TODO] CSS Stylesheet shenanigans

### ISSUE THREAD

**Issue by chonishi2id** [ecstaticstupidity/sp21-cse110-lab3#2]
**What needs to be done?**
Fill in created CSS Stylesheet with all elements in checklist below

- [x] Comment
- [x] Color (rgb, #FFF, hsl, color name)
- [x] Background (background color)
- [x] Unit (Use 3 unique relative and absolute units total)
- [x] Box Models
- [x] Long and Short Margins
- [x] Long and Short Padding
- [x] Borders (style, color, width, radius)
- [x] Text (color, decoration, align)
- [x] Display (none, block, inline-block, inline) AT LEAST 2
- [x] Sizing (height/width, max-width/min-width)
- [x] Position (static, relative, fixed, absolute, sticky) AT LEAST 2
- [x] Pseudo-class (:hover, :active)
- [x] Layouts (flexbox, grid)
- [x] Grid
- [x] Responsiveness (media query)
- [x] Fonts (use a third party font)

**How should this be implemented?**
Get on VSCode. Start with Comments. Work on color and background. Then work on margins, padding, and borders. Explore Units, borders, text, sizing, and display. Finally figure out the rest.

**When do you need this done by?**
Get it done by Sunday

**Comment by chonishi2id** [comment]
Finished comments, color, background, unit, box models, margins, padding, and borders
