### ISSUE TITLE
[TODO] CSS Selectors

### ISSUE THREAD

**Issue by chonishi2id** [ecstaticstupidity/sp21-cse110-lab3#3]
**What needs to be done?**
Add CSS Selectors to index.html. The following must be included

- [x] Class (.class)
- [x] ID (#id)
- [x] Universal (*)
- [x] Element (element)
- [x] Attribute ([attribute=foo])
- [x] Pseudo-class (p::hover)
- [x] Selector List (element, element) /*select multiple elements */
- [x] Combinators /*specify selections based on element positioning in the DOM tree */
- [x] Descendant Combinator (element element)
- [x] Child Combinator (element > element)
- [x] General Sibling Combinator (element ~ element)
- [x] Adjacent Sibling Combinator (element + element)
- [ ] Combining Two Selectors (element.class)

**How should this be implemented?**
Just cocaine cowboy this.

**When do you need this done by?**
Try Sunday but no shame if you have to push to Monday

**Additional context**
Optional Content:

- [ ] Transformations
- [ ] Animations
